# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_PINCTRL_MTK_V2)		+= pinctrl-mtk-common-v2.o
obj-$(CONFIG_PINCTRL_MTK_PARIS)		+= pinctrl-paris.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT8186)		+= pinctrl-mt8186.o
