image: debian:trixie

build:
  script: |
    set -exu
    apt-get update
    apt-get --yes install --no-install-recommends gcc-aarch64-linux-gnu build-essential bison flex lz4 device-tree-compiler git ca-certificates libssl-dev libusb-dev u-boot-tools
    ./build.sh
  artifacts:
    paths:
      - images/barebox-mnt-pocket-reform-rk3588.img
      - images/barebox-mnt-reform-next-rk3588.img
      - images/barebox-mnt-reform2-rk3588.img
      - images/barebox-mnt-reform2-dsi-rk3588.img
