image: debian:trixie

build:
  script: |
    set -exu
    apt-get update
    apt-get --yes install --no-install-recommends gcc-aarch64-linux-gnu build-essential bison flex gawk lz4 lzma-alone lzop device-tree-compiler pkgconf libtool git ca-certificates libssl-dev libusb-1.0-0-dev u-boot-tools libguestfs-tools genisoimage
    ./build.sh
  artifacts:
    paths:
      - images/barebox-mnt-pocket-reform-rk3588.img
      - images/barebox-mnt-reform-next-rk3588.img
      - images/barebox-mnt-reform2-rk3588.img
      - images/barebox-mnt-reform2-dsi-rk3588.img
