# SPDX-License-Identifier: GPL-2.0-only

obj-y += rockchip.o bootrom.o
pbl-$(CONFIG_ARCH_ROCKCHIP_ATF) += atf.o
obj-$(CONFIG_ARCH_RK3188) += rk3188.o
obj-$(CONFIG_ARCH_RK3288) += rk3288.o
obj-pbl-$(CONFIG_ARCH_PX30) += px30.o
obj-pbl-$(CONFIG_ARCH_RK3399) += rk3399.o
obj-pbl-$(CONFIG_ARCH_RK3568) += rk3568.o
obj-pbl-$(CONFIG_ARCH_RK3588) += rk3588.o
obj-$(CONFIG_ARCH_ROCKCHIP_RK_IMAGE_RKNS) += bootm-rkns.o
obj-$(CONFIG_ARCH_ROCKCHIP_RK_IMAGE_RK30) += bootm-rk30.o
obj-pbl-$(CONFIG_ARCH_ROCKCHIP_V8) += dmc.o
obj-$(CONFIG_BAREBOX_UPDATE) += bbu.o
