/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the code (mostly headers) for which Rust bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

/*
 * First, avoid forward references to `enum` types.
 *
 * This workarounds a `bindgen` issue with them:
 * <https://github.com/rust-lang/rust-bindgen/issues/3179>.
 *
 * Without this, the generated Rust type may be the wrong one (`i32`) or
 * the proper one (typically `c_uint`) depending on how the headers are
 * included, which in turn may depend on the particular kernel configuration
 * or the architecture.
 *
 * The alternative would be to use casts and likely an
 * `#[allow(clippy::unnecessary_cast)]` in the Rust source files. Instead,
 * this approach allows us to keep the correct code in the source files and
 * simply remove this section when the issue is fixed upstream and we bump
 * the minimum `bindgen` version.
 *
 * This workaround may not be possible in some cases, depending on how the C
 * headers are set up.
 */

#include <clock.h>
#include <errno.h>
#include <linux/bitmap.h>
#include <linux/sprintf.h>
#include <linux/bitops.h>
#include <asm-generic/bitops/ops.h>
#include <linux/clk.h>
#include <linux/iopoll.h>
#include <linux/ktime.h>
#include <linux/pagemap.h>
#include <linux/printk.h>
#include <linux/sizes.h>
#include <linux/string.h>
#include <malloc.h>
#include <stdlib.h>
