/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __ASM_GENERIC_GDB_SCRIPTS_H__
#define __ASM_GENERIC_GDB_SCRIPTS_H__

#define SECTION_SCRIPT_ID_PYTHON_FILE 1
#define SECTION_SCRIPT_ID_SCHEME_FILE 3
#define SECTION_SCRIPT_ID_PYTHON_TEXT 4
#define SECTION_SCRIPT_ID_SCHEME_TEXT 6

#endif /* __ASM_GENERIC_GDB_SCRIPTS_H__ */
