# SPDX-License-Identifier: GPL-2.0-only
obj-y += core.o synth.o
obj-$(CONFIG_SOUND_SDL)		+= sdl.o
obj-$(CONFIG_PWM_BEEPER) 	+= pwm-beeper.o
obj-$(CONFIG_GPIO_BEEPER)	+= gpio-beeper.o
obj-$(CONFIG_SOUND_ROCKCHIP_I2S) += rockchip_i2s.o
