title      Debian GNU/Linux forky/sid 
version    6.17.13-mnt-reform-arm64
linux      /vmlinuz-6.17.13-mnt-reform-arm64
initrd     /initrd.img-6.17.13-mnt-reform-arm64
devicetree /dtb-6.17.13-mnt-reform-arm64
options    ro no_console_suspend cryptomgr.notests

