/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the headers for which Rust UAPI bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <linux/mdio.h>
#include <linux/mii.h>
#include <linux/ethtool.h>
