#!/bin/bash

KBUILD_OUTPUT=${KBUILD_OUTPUT:-.}
LLVM_PROFILE_FILE=${LLVM_PROFILE_FILE=:-default.profraw}
LLVM_PROFILE_DATA=${LLVM_PROFILE_FILE%.profraw}.profdata

if [ -z "$LLVM" ]; then
    echo 'Only clang/LLVM is supported, but $LLVM is unset'
    exit 1
fi

if [[ "$LLVM" = */* ]]; then
LLVM_PREFIX=${LLVM_PREFIX:-${LLVM}}
elif [[ "$LLVM" = *-* ]]; then
LLVM_SUFFIX=${LLVM_SUFFIX:-${LLVM}}
fi

profdata=${LLVM_PREFIX}llvm-profdata${LLVM_SUFFIX}
cov=${LLVM_PREFIX}llvm-cov${LLVM_SUFFIX}

$profdata merge -sparse ${LLVM_PROFILE_FILE} -o ${LLVM_PROFILE_DATA}
$cov export --format=lcov ${KBUILD_OUTPUT}/barebox -instr-profile ${LLVM_PROFILE_DATA} > ${KBUILD_OUTPUT}/coverage.info
genhtml -o ${KBUILD_OUTPUT}/coverage_html ${KBUILD_OUTPUT}/coverage.info
