#!/bin/sh
# SPDX-License-Identifier: GPL-2.0

UTS_MACHINE=$1
CC_VERSION="$2"
LD=$3

# Fix the language to get consistent output
LC_ALL=C
export LC_ALL

if [ -z "$KBUILD_BUILD_TIMESTAMP" ]; then
	TIMESTAMP=`date`
else
	TIMESTAMP=$KBUILD_BUILD_TIMESTAMP
fi

if [ -z "$KBUILD_BUILD_VERSION" ]; then
	if [ -r .version ]; then
		VERSION=`cat .version`
	else
		VERSION=0
		echo 0 > .version
	fi
else
	VERSION=$KBUILD_BUILD_VERSION
fi

UTS_VERSION="#$VERSION"
UTS_VERSION="$UTS_VERSION $CONFIG_FLAGS $TIMESTAMP"

if test -z "$KBUILD_BUILD_USER"; then
	BAREBOX_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
else
	BAREBOX_COMPILE_BY=$KBUILD_BUILD_USER
fi
if test -z "$KBUILD_BUILD_HOST"; then
	BAREBOX_COMPILE_HOST=`uname -n`
else
	BAREBOX_COMPILE_HOST=$KBUILD_BUILD_HOST
fi

LD_VERSION=$(LC_ALL=C $LD -v | head -n1 |
		sed -e 's/(compatible with [^)]*)//' -e 's/[[:space:]]*$//')

cat <<EOF
#define UTS_MACHINE		"${UTS_MACHINE}"
#define UTS_VERSION		"${UTS_VERSION}"
#define BUILDSYSTEM_VERSION	"${BUILDSYSTEM_VERSION}"
#define BAREBOX_COMPILE_BY	"${BAREBOX_COMPILE_BY}"
#define BAREBOX_COMPILE_HOST	"${BAREBOX_COMPILE_HOST}"
#define BAREBOX_COMPILER	"${CC_VERSION}, ${LD_VERSION}"
EOF
