name: build images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/barebox/barebox/barebox-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev

    strategy:
      fail-fast: false
      matrix:
        arch: [mips, powerpc, riscv, sandbox, x86 ]
        regex: ["*"]
        include:
          - arch: arm
            regex: "[a-b]*"
          - arch: arm
            regex: "[c-m]*"
          - arch: arm
            regex: "[n-q]*"
          - arch: arm
            regex: "[r-z]*"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build
      run: |
        export ARCH=${{matrix.arch}}

        ./test/generate-dummy-fw.sh

        ./MAKEALL -O build-${{matrix.arch}} -k test/kconfig/disable_size_check.kconf \
                -k test/kconfig/disable_target_tools.kconf -e '${{matrix.regex}}'
