name: Pull Request Docs Check

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/barebox/barebox/barebox-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "Documentation/"
        build-command: "make docs"
